#!/bin/bash

GREEN='\e[32m'
NC='\e[0m'
COUNTER_SUCCESS=0
COUNTER_FAIL=0
DIFF_RES=""
TEST_FILES="test_files/grep_file1 test_files/grep_file2 test_files/grep_file3 test_files/grep_file4"
VALGRIND="valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind_result.txt"

printf "${GREEN}-----RUNNING EXTRA TESTS-----${NC}\n"

for var in -i -v -c -l -n -h -s -o
do
          TEST1="$var permission $TEST_FILES"
          $VALGRIND ./s21_grep $TEST1 > s21_grep.txt
          grep $TEST1 > grep.txt
          DIFF_RES="$(diff -s s21_grep.txt grep.txt)"
          if [ "$?" == 0 ]
            then
              (( COUNTER_SUCCESS++ ))
            else
              echo "$TEST1" >> log.txt
              (( COUNTER_FAIL++ ))
          fi
          rm s21_grep.txt grep.txt
done

for var in -i -v -c -l -n -h -s -o
do
  for var2 in -i -v -c -l -n -h -s -o
  do
        if [ $var != $var2 ]
        then
          TEST1="$var $var2 permission $TEST_FILES"
          ./s21_grep $TEST1 > s21_grep.txt
          grep $TEST1 > grep.txt
          DIFF_RES="$(diff -s s21_grep.txt grep.txt)"
          if [ "$?" == 0 ]
            then
              (( COUNTER_SUCCESS++ ))
            else
              echo "$TEST1" >> log.txt
              (( COUNTER_FAIL++ ))
          fi
          rm s21_grep.txt grep.txt
        fi
  done
done

for var in -i -v -c -l -n -h -s -o
do
  for var2 in -i -v -c -l -n -h -s -o
  do
      for var3 in -i -v -c -l -n -h -s -o
      do
        if [ $var != $var2 ] && [ $var2 != $var3 ] && [ $var != $var3 ]
        then
          TEST1="$var $var2 $var3 permission $TEST_FILES"
          ./s21_grep $TEST1 > s21_grep.txt
          grep $TEST1 > grep.txt
          DIFF_RES="$(diff -s s21_grep.txt grep.txt)"
          if [ "$?" == 0 ]
            then
              (( COUNTER_SUCCESS++ ))
            else
              echo "$TEST1" >> log.txt
              (( COUNTER_FAIL++ ))
          fi
          rm s21_grep.txt grep.txt

        fi
      done
  done
done

for var in -i -v -c -l -n -h -s -o
do
  for var2 in -i -v -c -l -n -h -s -o
  do
      for var3 in -i -v -c -l -n -h -s -o
      do
          for var4 in -i -v -c -l -n -h -s -o
          do
            if [ $var != $var2 ] && [ $var2 != $var3 ] && [ $var != $var3 ] && [ $var != $var4 ] && [ $var2 != $var4 ] && [ $var3 != $var4 ]
            then
              TEST1="$var $var2 $var3 $var4 permission $TEST_FILES"
              ./s21_grep $TEST1 > s21_grep.txt
              grep $TEST1 > grep.txt
              DIFF_RES="$(diff -s s21_grep.txt grep.txt)"
              if [ "$?" == 0 ]
                then
                  (( COUNTER_SUCCESS++ ))
                else
                  echo "$TEST1" >> log.txt
                  (( COUNTER_FAIL++ ))
              fi
              rm s21_grep.txt grep.txt

            fi
          done
      done
  done
done


[ "$COUNTER_FAIL" = 0 ] && echo "100% covered" || echo "$COUNTER_FAIL not passed check log.txt"

echo "SUCCESS: $COUNTER_SUCCESS"
echo "FAIL: $COUNTER_FAIL"
